#pragma once

namespace tcg_parser
{

#define EFIDP_PNP_EISA_ID_CONST 0x41d0

#define EFIDP_EISA_ID(_Name, _Num) ((uint32_t)((_Name) | (_Num) << 16))

#define EFIDP_EFI_PNP_ID(_PNPId) EFIDP_EISA_ID(EFIDP_PNP_EISA_ID_CONST, (_PNPId))

#define EFIDP_ACPI_PCI_ROOT_HID EFIDP_EFI_PNP_ID(0x0a03)
#define EFIDP_ACPI_CONTAINER_0A05_HID EFIDP_EFI_PNP_ID(0x0a05)
#define EFIDP_ACPI_CONTAINER_0A06_HID EFIDP_EFI_PNP_ID(0x0a06)
#define EFIDP_ACPI_PCIE_ROOT_HID EFIDP_EFI_PNP_ID(0x0a08)
#define EFIDP_ACPI_EC_HID EFIDP_EFI_PNP_ID(0x0a09)
#define EFIDP_ACPI_FLOPPY_HID EFIDP_EFI_PNP_ID(0x0604)
#define EFIDP_ACPI_KEYBOARD_HID EFIDP_EFI_PNP_ID(0x0301)
#define EFIDP_ACPI_SERIAL_HID EFIDP_EFI_PNP_ID(0x0501)
#define EFIDP_ACPI_PARALLEL_HID EFIDP_EFI_PNP_ID(0x0401)
#define EFIDP_ACPI_NVDIMM_HID EFIDP_EFI_ACPI_ID(0x0012)

}
